github:
  client:
    id: **********
    secret: *************
  redirect_url: http://localhost:8887/account/github/callback

server:
  port: 8887

spring:
  datasource:
    url: jdbc:h2:~/.h2/community
    data-username: sa
    data-password:
    driver-class-name: org.h2.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.huadao.community.model.*
  mapper-locations: classpath:mapper/*.xml
